'use client'
import Image from "next/image";
import { useRouter } from 'next/navigation';
import './globals.css'
import Notification_Example from './notifications/page'
import uswdsLogo from '@/public/comet-tech-partners-04.jpg'
export default function Home() {
  const router = useRouter();
  const config = [
    {
      cardTitle: "Notifications", 
      cardBody: "Bundled front end component for user notifications using USDWS alerts  based on multiple severity levels: INFO, SUCCESS, ERROR, WARNING, EMERGENCY.",
      route: "/notifications"
    },
    {
      cardTitle: "Email", 
      cardBody: "Displays notifications for user actions based on multiple severity levels: INFO, SUCCESS, ERROR, WARNING, EMERGENCY.",
      route: "/email"
    },
    {
      cardTitle: "File Handler", 
      cardBody: "Provide users with a user-friendly UI for file selection and progress tracking, an API for handling file transfers, a business component for processing and validating files, and an S3 storage endpoint for secure and scalable file storage. ",
      route: "/components/file_upload"
    },
    {
      cardTitle: "User Profile", 
      cardBody: "Captures and stores valuable information about subscribed users pertinent to the system's operation, allowing users to enter and manage their profile information and ensure that required information is provided before granting access to the system. ",
      route: "/components/user_profile"
    },
    {
      cardTitle: "User Authentication", 
      cardBody: "Verify the identity of a user by validating their provided username and password, should support an Multi-Factor Authentication (MFA) feature that can be easily included or excluded based on client requirements. ",
      route: "/components/user_auth"
    },
    {
      cardTitle: "Data Entry", 
      cardBody: "Provide a user-friendly interface for capturing and storing data in a structured manner. This component will include a UI for data input, an API for handling data submission, a business component for processing and storing the data, and a data store with a well-defined schema. ",
      route: "/components/data_entry"
    },
    {
      cardTitle: "Chatbot", 
      cardBody: "The purpose of the basic chat/help interface is to provide users with an interactive and user-friendly way to get assistance and answers to their questions. The interface will include a UI where users can engage in a conversation with a chatbot.",
      route: "/components/chatbot"
    },
    {
      cardTitle: "Dashboard", 
      cardBody: "The basic dashboard component provides users with a visually appealing and informative overview of key data points. The dashboard will include a UI displaying custom data in the form of one table and two graphical renderings.",
      route: "/components/dashboard"
    },
    {
      cardTitle: "Logging", 
      cardBody: "The purpose of the Logging component is to provide a centralized and structured way to record and store log entries generated by various parts of the system, supporting different log entry types (e.g., DEBUG, INFO, WARNING, ERROR) and allowing for easy retrieval of log entries while preserving their order.",
      route: "/components/logging"
    }
    
  ]

  const handleViewDemo = (route) => {
    router.push(route);
  };


  return (
    <div className="component-page" style={{
     
  }}>
      <div className="header-section">
      <h1 className="card-page-header mr-5">CTC Components</h1>
      <Image src={uswdsLogo} height={100} width={200}></Image>
      </div>
      <div className="card-group-wrapper">
      <ul className="usa-card-group">
        { config && config.map((card, index) => (
        <li key={index} className="usa-card tablet-lg:grid-col-6 widescreen:grid-col-4">
          <div className="usa-card__container">
            <div className="usa-card__header">
              <h4 className="usa-card__heading">{card.cardTitle}</h4>
            </div>
            <div className="usa-card__body">
              <p>
                {card.cardBody}
              </p>
            </div>
            <div className="usa-card__footer">
              <a href="#" className="usa-button" onClick={() => handleViewDemo(card.route)}>View Demo</a>
            </div>
          </div>
        </li>
        ))
        }
      </ul>
      </div>
    </div>

  );
}
